# Generated by Django 4.0.4 on 2022-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('aspects', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'consolidated_aspects',
            },
        ),
    ]
