# Generated by Django 4.0.4 on 2022-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdate',
            name='aspects',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterModelTable(
            name='sdate',
            table=None,
        ),
    ]
