# Generated by Django 4.0.4 on 2022-04-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0002_alter_sdate_aspects_alter_sdate_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdate',
            old_name='id',
            new_name='id_num',
        ),
    ]
