# Generated by Django 4.0.4 on 2022-05-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0004_alter_sdate_aspects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdate',
            old_name='date',
            new_name='sdate',
        ),
    ]
