# Generated by Django 4.0.4 on 2022-05-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0005_rename_date_sdate_sdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdate',
            old_name='sdate',
            new_name='s_date',
        ),
    ]
