# Generated by Django 4.0.4 on 2022-05-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0006_rename_sdate_sdate_s_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdate',
            old_name='s_date',
            new_name='date',
        ),
    ]
